// <auto-generated />
using System;
using HPT.Infrastructure.Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HPT.Infrastructure.Migrations
{
    [DbContext(typeof(ContextHp))]
    [Migration("20181210203459_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HPT.ApplicationCore.Entity.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(150)");

                    b.Property<int>("ReservaId");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("HPT.ApplicationCore.Entity.Endereco", b =>
                {
                    b.Property<int>("EnderecoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CEP")
                        .HasColumnType("varchar(150)");

                    b.Property<int>("HospedeId");

                    b.Property<string>("Logradouro")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Numero")
                        .HasColumnType("varchar(40)");

                    b.HasKey("EnderecoId");

                    b.HasIndex("HospedeId")
                        .IsUnique();

                    b.ToTable("enderecos");
                });

            modelBuilder.Entity("HPT.ApplicationCore.Entity.Historico", b =>
                {
                    b.Property<int>("HistoricoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateHora");

                    b.Property<string>("Detalhe")
                        .HasColumnType("varchar(200)");

                    b.HasKey("HistoricoId");

                    b.ToTable("Historicos");
                });

            modelBuilder.Entity("HPT.ApplicationCore.Entity.Hospede", b =>
                {
                    b.Property<int>("HospedeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ReservaId");

                    b.HasKey("HospedeId");

                    b.HasIndex("ReservaId");

                    b.ToTable("Hospedes");
                });

            modelBuilder.Entity("HPT.ApplicationCore.Entity.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoriaId");

                    b.Property<DateTime>("DataEntrada");

                    b.Property<DateTime>("DataSaida");

                    b.Property<int>("HospedeId");

                    b.Property<int>("NumeroQuad");

                    b.Property<decimal>("Valor");

                    b.HasKey("ReservaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("HPT.ApplicationCore.Entity.ReservaHistorico", b =>
                {
                    b.Property<int>("ReservaHistoricoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HistoricoId");

                    b.Property<int>("ReservaId");

                    b.HasKey("ReservaHistoricoId");

                    b.HasIndex("HistoricoId");

                    b.HasIndex("ReservaId");

                    b.ToTable("ReservaHistoricos");
                });

            modelBuilder.Entity("HPT.ApplicationCore.Entity.Endereco", b =>
                {
                    b.HasOne("HPT.ApplicationCore.Entity.Hospede", "Hospedes")
                        .WithOne("Endereco")
                        .HasForeignKey("HPT.ApplicationCore.Entity.Endereco", "HospedeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HPT.ApplicationCore.Entity.Hospede", b =>
                {
                    b.HasOne("HPT.ApplicationCore.Entity.Reserva", "Reserva")
                        .WithMany("Hospedes")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HPT.ApplicationCore.Entity.Reserva", b =>
                {
                    b.HasOne("HPT.ApplicationCore.Entity.Categoria", "Categoria")
                        .WithMany("Reservas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HPT.ApplicationCore.Entity.ReservaHistorico", b =>
                {
                    b.HasOne("HPT.ApplicationCore.Entity.Historico", "Historico")
                        .WithMany("ReservaHistoricos")
                        .HasForeignKey("HistoricoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HPT.ApplicationCore.Entity.Reserva", "Reserva")
                        .WithMany("ReservaHistoricos")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
